server:
  port: 8000
  servlet:
    context-path: /AMQNU/api/
  tomcat:
    max-swallow-size: 50MB

spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:mysql://localhost:3306/qnu"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 60000
  mail:
    host: smtp.gmail.com
    port: 587
    username: epicescapesnews@gmail.com
    password: zrtoehywklazjaui
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.flywaydb: INFO
    org.springdoc: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /document/api-docs
  swagger-ui:
    path: /document/swagger-ui.html




