server:
  port: 8000
  servlet:
    context-path: /AMQNU/api/
  tomcat:
    max-swallow-size: 50MB

spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:mysql://localhost:3306/qnu"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.flywaydb: INFO
    org.springdoc: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /document/api-docs
  swagger-ui:
    path: /document/swagger-ui.html

jwt:
  signerKey: "EIG2ryG3InsGo7mStNgivMrw2/OpHD4UrBJUPwkSWacWJaEztRuqsr/axSiuCTxZ"


